tscircuit/runframe

lib/components/RunFrame.tsx
tests/RunFrame.test.tsx

Issue - https://github.com/tscircuit/snippets-cli/issues/7
https://github.com/user-attachments/assets/a905858b-156f-45c2-87b7-e7a9e68c57d3

feat: Show error in tab

---

package.json

Gives the error that the version is already present

update the version of package

---

lib/components/RunFrameWithApi/RunFrameWithApi.tsx
lib/components/RunFrameWithApi/store.ts
lib/components/RunFrameWithApi/types.ts
src/main.tsx

- **use run frame for cli as default static build target**
- **load initial files via list**

List files prior to starting

---

lib/components/RunFrameWithApi/RunFrameWithApi.tsx
lib/components/RunFrameWithApi/store.ts
lib/components/RunFrameWithApi/types.ts
src/main.tsx

- **use run frame for cli as default static build target**
- **load initial files via list**
- **logging for selected entrypoint**

Logging for selected entrypoint, load files initially

---

lib/components/RunFrame.tsx

fix: will show import error message + allow to rerun if any worker err occurs

---

lib/components/CircuitJsonPreview.tsx
lib/components/CircuitJsonPreviewStandalone/standalone-preview.tsx
package.json
vite.config.ts

- standalone-preview added
- Prop to toggle the rightHeaderContent

Add standalone CircuitJsonPreview

---

lib/components/CircuitJsonPreview/CircuitJsonPreview.tsx

feat: show runframe version

---

bun.lock
examples/example12-event-emitting.fixture.tsx
lib/components/CircuitJsonPreview/CircuitJsonPreview.tsx
lib/components/RunFrame/RunFrame.tsx
package.json

we might need to add a small timeout to reduce the example output
https://github.com/user-attachments/assets/581770fc-97ac-496a-b8b0-80281aab079b

emitting onEditEvents with an example

---

lib/components/RunFrame/RunFrame.tsx

close https://github.com/tscircuit/tscircuit.com/issues/719

Feat: add ctrl/cmd+enter run feature

---

lib/components/RunFrame/RunFrame.tsx

use simpler expression for simplifying error text to avoid cutting off important text

---

examples/example13-runframe-with-api-manual-edits.fixture.tsx

CC @imrishabh18 this is the fix for example13!

fix example13 (bad entrypoint)

---

bun.lock
package.json

let's see how it looks in tscircuit.com

updated schematic-viewer

---

lib/utils/get-registry-ky.ts
vite.config.ts

- **Example of how to get auth token**
- **getRegistryKy to incorporate token**

Add auth tokens, setup for proxying to local registry for testing

---

examples/example17-simple.fixture.tsx
lib/components/CircuitJsonPreview/CircuitJsonPreview.tsx

dark reader extension friendly colors

---

lib/components/ErrorTabContent/ErrorTabContent.tsx

fix https://github.com/tscircuit/tscircuit.com/issues/1232
resolve https://github.com/tscircuit/runframe/issues/666
https://github.com/user-attachments/assets/434fd6e8-207c-44a6-9441-5eb2f8f00452

fix(ErrorTabContent): improve error tab errors, remove stacking or errors and content

---

lib/components/CircuitJsonPreview/CircuitJsonPreview.tsx
lib/hooks/use-fullscreen-body-scroll.ts

https://github.com/user-attachments/assets/aff17689-95f3-4aac-9d72-a9806ba29d3d
fix https://github.com/tscircuit/tscircuit.com/issues/1094

feat(CircuitJsonPreview): disable scrolling in fullscreen mode

---

bun.lock
package.json

Reverts tscircuit/runframe#766

Revert "fix(deps): update dependency @tscircuit/footprinter to ^0.0.181"

---

lib/components/CircuitJsonPreview/CircuitJsonPreview.tsx

fix #749
https://github.com/user-attachments/assets/142cd331-3f2d-44ff-9462-0c2ef0299c39

feat: presistant tabs whenver errors occurs

---

.github/workflows/branch-release.yml
package.json

- **bundle deps**
- **add branch release**

Add branch release, move everything to dev dep

---

lib/components/RunFrame/RunFrame.tsx
lib/components/RunFrameForCli/RunFrameForCli.tsx
lib/components/RunFrameWithApi/RunFrameWithApi.tsx
lib/components/RunFrameWithApi/standalone.tsx

next step: Modify `tscircuit`'s copy-runframe-standalone script to modify this variable to set to the latest from cdnjs

add mechanism for injecting a CDN url for the webworker blob

---

examples/example25-voltage-divider.fixture.tsx
lib/components/CircuitJsonPreview/CircuitJsonPreview.tsx

feat: enable SPICE simulation + voltage divider test circuit

---

lib/components/FileMenuLeftHeader.tsx
lib/components/RunFrameStaticBuildViewer/RunFrameStaticBuildViewer.tsx

adjust zindex in FileMenuLeftHeader

---

bun.lock
package.json

See https://github.com/tscircuit/tscircuit.com/pull/1727

chore: update easyeda to version 0.0.228
